import Head from "next/head";

const HeloPage = () => {
  return (
    <>
      <Head>
        <title>About Page | @driannaird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="bg-blue-500">hi</h1>
    </>
  );
};

export default HeloPage;
