import AboutView from "@/views/about/AboutView";
import Head from "next/head";

const AboutPage = () => {
  return (
    <>
      <Head>
        <title>About Page | @driannaird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/me.jpg" />
      </Head>
      <main>
        <AboutView />
      </main>
    </>
  );
};

export default AboutPage;
