import ContactView from "@/views/contact/ContactView";
import Head from "next/head";

const ContactPage = () => {
  return (
    <>
      <Head>
        <title>Contact Page | @driannaird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/me.jpg" />
      </Head>
      <main>
        <ContactView />
      </main>
    </>
  );
};

export default ContactPage;
