import Head from "next/head";
import HomeView from "@/views/home/HomeView";
import { ProjectsType } from "@/types/ProjectsTypes";
import { axiosInstance } from "@/utils/axios/axiosInstance";

export default function Home({ projects }: { projects: ProjectsType }) {
  return (
    <>
      <Head>
        <title>Home Page | @driannaird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeView projects={projects} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await axiosInstance.get("/api/projects");
  const data = response.data.data;

  return {
    props: {
      projects: data,
    },
  };
}
