import { ProjectsType } from "@/types/ProjectsTypes";
import { axiosInstance } from "@/utils/axios/axiosInstance";
import ProjectView from "@/views/project/ProjectView";
import Head from "next/head";

const ProjectPage = ({ projects }: { projects: ProjectsType }) => {
  return (
    <>
      <Head>
        <title>About Page | @driannaird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/me.jpg" />
      </Head>
      <main>
        <ProjectView projects={projects} />
      </main>
    </>
  );
};

export default ProjectPage;

export async function getServerSideProps() {
  const response = await axiosInstance.get("/api/projects");
  const data = response.data.data;

  const sortedData = data.sort(
    (a: { idProject: number }, b: { idProject: number }) =>
      b.idProject - a.idProject
  );

  return {
    props: {
      projects: sortedData,
    },
  };
}
